### ISSUE TITLE
Page Whatch

### ISSUE THREAD

**Issue by LumenH** [Infinit8io/Swatching#6]
Mettre un bouton flottant pour le "I will watch it"
Les boutons sont moyens, il y aurait possibilité d'un système slide gauche-droite comme sur Tinder
#workshop

**Comment by Ishydo** [comment]
Nous avons pris la décision de garder le bouton uniquement dans le header pour le moment. Le système à la Tinder est remplacé par un "shake" : il faut secouer légèrement le téléphone pour changer de film 😄
